### ISSUE TITLE
Switching branches and Octotree stays on master :-(

### ISSUE THREAD

**Issue by SchumacherFM** [buunguyen/octotree#169]
Great extension! Good work!

I'm not sure if this is a known bug and I also can't find anything in the closed issues.

See the print screen where the discrepancy is:

![screen shot 2015-06-03 at 11 17 14 am](https://cloud.githubusercontent.com/assets/372027/7950870/d6a3d824-09e3-11e5-9606-a5a730c95751.png)

Repository for testing: https://github.com/Cotya/magento-composer-installer

Octotree Version 1.6.1
Chrome: Version 43.0.2357.81 (64-bit) on OSX 10.9

Thanks for having a look into it!

**Comment by buunguyen** [comment]
Fixed. Will be up in store soon.

**Comment by SchumacherFM** [comment]
Thank you!

**Comment by sharduul** [comment]
Is this available in store yet? I have the same problem still.
